"""empty message

Revision ID: e67e7370eb92
Revises: b6767c22dcfb
Create Date: 2019-04-22 20:04:57.118582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67e7370eb92'
down_revision = 'b6767c22dcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
